<FirstScreen>:
    GridLayout:
        padding:10
        spacing:10
        cols: 1
        Image:
            id: img
            size_hint_y: 0.8
        TextInput:
            id: user_query
            size_hint_y: 0.1
        Button:
            size_hint_y: 0.1
            text: 'Search'
            on_press: root.set_image()

<RootWidget>:
    FirstScreen:
        id: first_screen
        name: 'first_screen'